[build]
  publish = "public/"
  command = "npm run build"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

  [[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "public/assets/images", # Processed images - adjust to match your outputDir
    ".cache" # Remote Assets
  ]
  [[plugins]]
  package = "netlify-plugin-image-optimization"
  [plugins.inputs]
    quality = 80
    formats = ["webp", "jpeg", "png"] # Ensure WebP is supported alongside other formats.
